//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class character
    {
        public int id { get; set; }
        public string name { get; set; }
        public string element { get; set; }
        public string stars { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image { get; set; }
    }
}
